language: ruby
sudo: required
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
notifications:
  email:
   - raphael.pinson@camptocamp.com
env:
# base env
  # Most tests with oldest supported ruby-augeas
  - PUPPET=2.7.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0
  - PUPPET=3.0.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0
  - PUPPET=3.2.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0
  - PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0
  # Test the latest ruby-augeas (~>)
  - PUPPET=3.2.0 RUBY_AUGEAS=0.5
    # Use this build to publish on the forge
  - PUPPET=3.4 RUBY_AUGEAS=0.5 FORGE_PUBLISH=true
  # Test other versions of Augeas
  - PUPPET=2.7.0 RUBY_AUGEAS=0.3.0 AUGEAS=0.10.0
  - PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=0.10.0
  - PUPPET=2.7.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.0.0
  - PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.0.0
  - PUPPET=2.7.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0
  - PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0
  - PUPPET=2.7.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.2.0
  - PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.2.0
  # Issue #83: test old Augeas with new lenses
  - PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.0.0 LENSES=HEAD
  - PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0 LENSES=HEAD
  - PUPPET=3.4 RUBY_AUGEAS=0.5 AUGEAS=1.0.0 LENSES=HEAD
  - PUPPET=3.4 RUBY_AUGEAS=0.5 AUGEAS=1.1.0 LENSES=HEAD
  # Test latest Puppet version
  - PUPPET=4.0 RUBY_AUGEAS=0.5


matrix:
  fast_finish: true
  exclude:
# base exclude
    # No support for Ruby 2.0 before Puppet 3.2.0 and ruby-augeas 0.5
    - rvm: 2.0.0
      env: PUPPET=2.7.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0
    - rvm: 2.0.0
      env: PUPPET=3.0.0 RUBY_AUGEAS=0.3.0
    - rvm: 2.0.0
      env: PUPPET=3.2.0 RUBY_AUGEAS=0.3.0
    - rvm: 2.0.0
      env: PUPPET=3.4 RUBY_AUGEAS=0.3.0
    - rvm: 2.0.0
      env: PUPPET=2.7.0 RUBY_AUGEAS=0.3.0 AUGEAS=0.10.0
    - rvm: 2.0.0
      env: PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=0.10.0
    - rvm: 2.0.0
      env: PUPPET=2.7.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.0.0
    - rvm: 2.0.0
      env: PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.0.0
    - rvm: 2.0.0
      env: PUPPET=2.7.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0
    - rvm: 2.0.0
      env: PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0
    - rvm: 2.0.0
      env: PUPPET=2.7.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.2.0
    - rvm: 2.0.0
      env: PUPPET=3.0.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0
    - rvm: 2.0.0
      env: PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.2.0
    - rvm: 2.0.0
      env: PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.0.0 LENSES=HEAD
    - rvm: 2.0.0
      env: PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0 LENSES=HEAD
    # No support for Ruby 1.8 in Puppet 4
    - rvm: 1.8.7
      env: PUPPET=4.0 RUBY_AUGEAS=0.5


install:
  - "travis_retry ./.travis.sh"
script:
  - AUGEAS_LENS_LIB=lib/augeas/lenses:augeas/lenses bundle exec rake
  # Do not include the augeas/ directory in the deployed module
  - rm -rf augeas/
deploy:
  provider: puppetforge
  user: herculesteam
  password:
    secure: "AMqmhJcmD+R8cYvSY9rz2VAb8KDgxmnUO+hZb4HvKpM5Auf9oFibVpRWwwSerN75fFiiL8jn5Zwj5HhmyWr+lWr/x4wsHoQAGwJCoXTE40E+6Ick3DEi8rbvBYJIuBPrGcxW3PxH11uIAy27DBJ21Mp/OzIhKpTmVFv7sPrYr+c="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish if our main Ruby target builds
    rvm: 1.9.3
    condition: "$FORGE_PUBLISH = true"
