HOSTS:
  server:
    roles:
      - server
      - default
      - master
    platform:   el-7-x86_64
    box:        puppetlabs/centos-7.2-64-nocm
    box_url:    https://vagrantcloud.com/puppetlabs/boxes/centos-7.2-64-nocm
    hypervisor: vagrant
  centos-client:
    roles:
      - agent
      - client
    platform:   el-6-x86_64
    box:        puppetlabs/centos-6.6-64-nocm
    box_url:    https://vagrantcloud.com/puppetlabs/boxes/centos-6.6-64-nocm
    hypervisor: vagrant
# Needs testing
#  ubuntu-client:
#    roles:
#      - agent
#      - client
#    platform:   ubuntu-14.04-x86_64
#    box:        puppetlabs/ubuntu-14.04-64-nocm
#    box_url:    https://vagrantcloud.com/puppetlabs/boxes/ubuntu-14.04-64-nocm
#    hypervisor: vagrant
CONFIG:
  log_level: verbose
  type:      foss
  vagrant_memsize: 256
  ## vb_gui: true
