fixtures:
  repositories:
    apt:
      repo: "https://github.com/puppetlabs/puppetlabs-apt"
      ref: "2.1.0"
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
      ref: "4.6.0"
    java: "https://github.com/puppetlabs/puppetlabs-java"
    zypprepo: "https://github.com/deadpoint/puppet-zypprepo.git"
    archive: "https://github.com/voxpupuli/puppet-archive.git"
    systemd: "https://github.com/camptocamp/puppet-systemd"
    transition: "https://github.com/puppetlabs/puppetlabs-transition"
  symlinks:
    "jenkins": "#{source_dir}"
