---
language: ruby
bundler_args: --without development
before_install:
  - rm Gemfile.lock || true
  - gem update bundler
rvm:
  - 1.9.3
  - 2.1
  - 2.2
script: bundle exec rake test
env:
  - PUPPET_VERSION="~> 4.4.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.5.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.6.0" STRICT_VARIABLES=yes
sudo: false
